version: '2.0'

services:
  ui:
    image: instedd/aida-ui:dev
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://root:@db/aida-ui
      SECRET_KEY_BASE: secret
      SETTINGS__BACKEND__URL: http://backend/
      SETTINGS__BACKEND__PUBLIC_SOCKET_URL: ws://localhost:3000/socket
      SETTINGS__BACKEND__PUBLIC_CONTENT_URL: http://localhost:3000/content
      SETTINGS__BASE_URL: http://localhost:3000
      GUISSO_CLIENT_ID:     --- REGISTER APP AT login.instedd.org ---
      GUISSO_CLIENT_SECRET: --- REGISTER APP AT login.instedd.org ---
      VIRTUAL_HOST: '*'

  backend:
    image: instedd/aida:dev
    depends_on:
      - db
    environment:
      DATABASE_URL: ecto://root:@db/aida-backend
      VIRTUAL_HOST: '*/callback, */callback/*, */socket, */socket/*, */content, */content/*'
      VIRTUAL_HOST_WEIGHT: 1
    command: /bin/sh -c 'mix ecto.migrate && mix phx.server'

  db:
    image: postgres:9.6
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD:
    volumes:
      - db:/var/lib/postgresql/data

  proxy:
    image: 'dockercloud/haproxy:1.6.7'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    links:
      - ui
      - backend
    ports:
      - '3000:80'

  jobs:
    <<: *base
    command: /bin/sh -c './bin/rake jobs:work'

volumes:
  db:
